[package]
name = "puissance_4"
version = "0.1.0"
authors = ["Antony Merle <antony.merle@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1"